export const WEBSOCKET_OPEN = "WEBSOCKET_OPEN";
export const WEBSOCKET_OPENED = "WEBSOCKET_OPENED";

export const WEBSOCKET_CLOSE = "WEBSOCKET_CLOSE";
export const WEBSOCKET_CLOSED = "WEBSOCKET_CLOSED";

export const BUS_VEHICLE_DATA_REQUEST = "BUS_VEHICLE_DATA_REQUEST";
export const BUS_VEHICLE_DATA_SUCCESS = "BUS_VEHICLE_DATA_SUCCESS";
export const BUS_VEHICLE_DATA_FAILURE = "BUS_VEHICLE_DATA_FAILURE";
