export const WEBSOCKET_OPEN = "WEBSOCKET_OPEN";
export const WEBSOCKET_OPENED = "WEBSOCKET_OPENED";

export const WEBSOCKET_CLOSE = "WEBSOCKET_CLOSE";
export const WEBSOCKET_CLOSED = "WEBSOCKET_CLOSED";

export const REDUX_WEBSOCKET_MESSAGE = "REDUX_WEBSOCKET::MESSAGE";

export const BUS_VEHICLE_DATA_REQUEST = "BUS_VEHICLE_DATA_REQUEST";
export const BUS_VEHICLE_DATA_SUCCESS = "BUS_VEHICLE_DATA_SUCCESS";
export const BUS_VEHICLE_DATA_FAILURE = "BUS_VEHICLE_DATA_FAILURE";
export const BUS_VEHICLE_DATA_SET_QUERY = "BUS_VEHICLE_DATA_SET_QUERY";

export const BUS_VEHICLE_SELECT = "BUS_VEHICLE_SELECT";
export const BUS_VEHICLE_UNSELECT = "BUS_VEHICLE_UNSELECT";
