export const WEBSOCKET_OPEN = "WEBSOCKET_OPEN";
export const WEBSOCKET_OPENED = "WEBSOCKET_OPENED";

export const WEBSOCKET_CLOSE = "WEBSOCKET_CLOSE";
export const WEBSOCKET_CLOSED = "WEBSOCKET_CLOSED";
