name: main

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: ghcr.io/chuhlomin/busnj-console-ui

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '14.3.0'

      - run: npm install
      - run: npm run test
      - run: npm run build
        env:
          REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          REACT_APP_BUS_VEHICLE_DATA: https://console.busnj.chuhlomin.com/busVehicleData
          REACT_APP_BUS_VEHICLE_DATA_STREAM: wss://console.busnj.chuhlomin.com/busVehicleDataStream

      - name: Build and push to CR
        uses: chuhlomin/actions/docker-build-push@main
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PKG_TOKEN }}
          image_name: ${{ env.DOCKER_IMAGE }}
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Deploy to GKE
        uses: chuhlomin/actions/deploy-gke@main
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
          cluster_name: cluster-east
          location: us-east4-c
          vars: |
            app: busnj-console-ui
            image: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
            replicas: 1
          rollout_status_wait: deployment/busnj-console-ui
